version: "3.8"
services:
  vite-application:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules # Prevents overwriting node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: ["npm", "run", "dev", "--", "--host"]
    networks:
      - td_network # 🔹 Add this to share the network with backend

networks:
  td_network:
    external: true # Use the same network as the backend
